# Generated by Django 5.2.7 on 2025-11-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
